# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:


require 'yaml'
if File.file?('config.yaml')
  conf = YAML.load_file('config.yaml')
else
  raise "Configuration file 'config.yaml' does not exist."
end

IP = conf["ip"]

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
 
  # Provision  Nodes
  config.vm.define "lab-vm" do |node|
    # Name shown in the GUI
    node.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = "lab-vm"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpus"]
    end
    node.vm.hostname = "lab-vm"
    node.vm.network :private_network, ip: IP
    node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "../scripts/allow-bridge-nf-traffic.sh"
    if conf["install_docker"] == true
      node.vm.provision "install-docker", type: "shell", :path => "../scripts/install-docker.sh"
    end 

  end

end
