# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

require 'yaml'
if File.file?('config.yaml')
  conf = YAML.load_file('config.yaml')
else
  raise "Configuration file 'config.yaml' does not exist."
end

# Define the number of worker nodes
NUM_WORKER_NODES = 2

IP = "192.168.10."
MASTER_IP_START = 10
WORKERS_IP_START = 20

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provision Master Node
  config.vm.define "master" do |node|
    # Name shown in the GUI
    node.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-master"
        vb.memory = conf["master"]["memory"]
        vb.cpus = conf["master"]["cpus"]
    end
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: IP + "#{MASTER_IP_START}"
    node.vm.network "forwarded_port", guest: 22, host: "#{2710}"

    node.vm.provision "setup-hosts", :type => "shell", :path => "../scripts/setup-k8s-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end

    node.vm.provision "setup-dns", type: "shell", :path => "../scripts/update-dns.sh"
    node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "../scripts/allow-bridge-nf-traffic.sh"
    if conf["install_docker"] == true
      node.vm.provision "install-docker", type: "shell", :path => "../scripts/install-docker.sh"
    end 

  end

  # Provision worker nodes
  (1..NUM_WORKER_NODES).each do |i|
      config.vm.define "worker-#{i}" do |node|
        # Name shown in the GUI
        node.vm.provider "virtualbox" do |vb|
            vb.name = "k8s-worker-#{i}"
            vb.memory = conf["workers"]["memory"]
            vb.cpus = conf["workers"]["cpus"]
        end
        node.vm.hostname = "worker-#{i}"
        node.vm.network :private_network, ip: IP + "#{WORKERS_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"

        node.vm.provision "setup-hosts", :type => "shell", :path => "../scripts/setup-k8s-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end

        node.vm.provision "setup-dns", type: "shell", :path => "../scripts/update-dns.sh"
        node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "../scripts/allow-bridge-nf-traffic.sh"
        if conf["install_docker"] == true
          node.vm.provision "install-docker", type: "shell", :path => "../scripts/install-docker.sh"
        end 

      end
  end


end
